language: java

jdk:
  - openjdk8

addons:
  apt:
    packages:
    - ant
    - graphviz
    - tidy

script: travis_wait ant checklineends

os:
  - linux
#  - osx # Travis OS X support does not include Java

sudo: required
